/var/log/syslog {
    daily            # rotate logs daily
    # retention period of 7 days
    rotate 7
    compress         # compress old logs to save space
    missingok        # don't break if the log file is missing
    notifempty       # don't rotate if the log file is empty
    copytruncate     # copy current logs to new file, empty original file, so process keeps on writing to original file
}
